# Generated by Django 6.0.3 on 2026-04-07 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('full_address', models.CharField(blank=True, default='', max_length=300)),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='restaurant_categories/icons/%Y/%m/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurant_categories/banners/%Y/%m/')),
            ],
            options={
                'db_table': 'restaurant_categories',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurants.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/%Y/%m/')),
                ('short_description', models.TextField(blank=True, default='')),
                ('cr_number', models.CharField(blank=True, default='', max_length=20)),
                ('vat_number', models.CharField(blank=True, default='', max_length=20)),
                ('cr_document', models.FileField(blank=True, null=True, upload_to='restaurants/docs/cr/%Y/%m/')),
                ('vat_certificate', models.FileField(blank=True, null=True, upload_to='restaurants/docs/vat/%Y/%m/')),
                ('short_address', models.CharField(blank=True, default='', max_length=200)),
                ('street_name', models.CharField(blank=True, default='', max_length=200)),
                ('building_number', models.CharField(blank=True, default='', max_length=20)),
                ('building_secondary_number', models.CharField(blank=True, default='', max_length=20)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('unit_number', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='Saudi Arabia', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurants.restaurantcategory')),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='RestaurantBankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(choices=[('al_rajhi', 'Al Rajhi Bank'), ('snb', 'Saudi National Bank'), ('riyad', 'Riyad Bank'), ('samba', 'Samba Financial Group'), ('alinma', 'Alinma Bank'), ('bsf', 'Banque Saudi Fransi'), ('arab', 'Arab National Bank'), ('sib', 'Saudi Investment Bank'), ('other', 'Other')], max_length=50)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=34)),
                ('bank_iban_pdf', models.FileField(upload_to='restaurants/bank/%Y/%m/')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_bank_details',
            },
        ),
        migrations.CreateModel(
            name='BranchOpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('shifts', models.JSONField(default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurants.branch')),
            ],
            options={
                'db_table': 'branch_opening_hours',
                'unique_together': {('branch', 'day')},
            },
        ),
    ]
