# Generated by Django 6.0.3 on 2026-03-30 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='full_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='branch',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='brand_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='building_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='building_secondary_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('fast_food', 'Fast Food'), ('casual', 'Casual Dining'), ('fine_dining', 'Fine Dining'), ('cafe', 'Café'), ('bakery', 'Bakery'), ('pizza', 'Pizza'), ('sushi', 'Sushi'), ('shawarma', 'Shawarma'), ('seafood', 'Seafood'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(blank=True, default='Saudi Arabia', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cr_document',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cr_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='legal_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='short_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_certificate',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/docs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='RestaurantBankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(choices=[('al_rajhi', 'Al Rajhi Bank'), ('snb', 'Saudi National Bank'), ('riyad', 'Riyad Bank'), ('samba', 'Samba Financial Group'), ('alinma', 'Alinma Bank'), ('bsf', 'Banque Saudi Fransi'), ('arab', 'Arab National Bank'), ('sib', 'Saudi Investment Bank'), ('other', 'Other')], max_length=50)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=34)),
                ('bank_iban_pdf', models.FileField(upload_to='restaurants/bank/%Y/%m/')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_bank_details',
            },
        ),
        migrations.CreateModel(
            name='BranchOpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('shifts', models.JSONField(default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='restaurants.branch')),
            ],
            options={
                'db_table': 'branch_opening_hours',
                'unique_together': {('branch', 'day')},
            },
        ),
    ]
