# Generated by Django 6.0.3 on 2026-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
