# Generated by Django 6.0.3 on 2026-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_branch_full_address_branch_min_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='Saudi Arabia', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cr_document',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/docs/cr/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='vat_certificate',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/docs/vat/%Y/%m/'),
        ),
    ]
