# Generated by Django 6.0.3 on 2026-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_name_alter_branch_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cr_copy',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/docs/cr_copy/%Y/%m/'),
        ),
    ]
