# Generated by Django 6.0.3 on 2026-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_branch_email_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
