# Generated by Django 6.0.3 on 2026-03-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_cr_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cr_copy',
        ),
    ]
