# Generated by Django 6.0.3 on 2026-04-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_branch_closing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='closing_date',
            new_name='closing_day',
        ),
    ]
