# Generated by Django 6.0.3 on 2026-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_closing_date_branch_closing_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantcategory',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
