# Generated by Django 6.0.3 on 2026-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/covers/%Y/%m/'),
        ),
    ]
