# Generated by Django 6.0.3 on 2026-04-05 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_remove_restaurant_cr_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.branch')),
            ],
            options={
                'db_table': 'menu_categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
