# Generated by Django 6.0.3 on 2026-04-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
    ]
