# Generated by Django 6.0.3 on 2026-04-05 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0001_initial'),
        ('restaurants', '0005_remove_restaurant_cr_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='menu/items/%Y/%m')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, default='')),
                ('extra_prep_time', models.PositiveSmallIntegerField(default=0, help_text='Extra Minutes')),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dietary_info', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_menus.menucategories')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
