# Generated by Django 6.0.3 on 2026-04-05 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0003_modifiergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('option_type', models.CharField(choices=[('addition', 'Addition'), ('free', 'Free')], default='free', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='food_menus.modifiergroup')),
            ],
            options={
                'db_table': 'menu_modifier_options',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
