# Generated by Django 6.0.3 on 2026-04-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0004_modifieroption'),
        ('restaurants', '0005_remove_restaurant_cr_copy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategories',
            new_name='MenuCategory',
        ),
    ]
