# Generated by Django 6.0.3 on 2026-04-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0005_rename_menucategories_menucategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
