# Generated by Django 6.0.3 on 2026-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menus', '0006_menucategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiergroup',
            name='max_select',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
