# Generated by Django 6.0.3 on 2026-04-22 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_customercar_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage_active', models.BooleanField(default=False)),
                ('fixed_sar', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fixed_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commission_settings',
            },
        ),
    ]
