# Generated by Django 6.0.3 on 2026-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_commissiontransaction_ownerwallet_payoutrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
