# Generated by Django 6.0.3 on 2026-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_visibilitysettings_adminmanager_customerwallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('wallet', 'Wallet')], max_length=10),
        ),
    ]
