# Generated by Django 6.0.3 on 2026-03-27 06:19

import apps.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True, validators=[apps.utils.validators.validate_phone])),
                ('country_code', models.CharField(blank=True, default='+966', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('full_Name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('owner', 'Owner'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'indexes': [models.Index(fields=['role', 'is_active'], name='auth_user_role_fb77f3_idx'), models.Index(fields=['email'], name='auth_user_email_ece7f7_idx')],
            },
        ),
    ]
