# Generated by Django 6.0.3 on 2026-04-07 10:46

import apps.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('change_phone', 'Change Phone'), ('password_reset', 'Password Reset'), ('owner_register', 'Owner Register')], max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField()),
                ('verification_token', models.CharField(blank=True, db_index=True, help_text='Short-lived token returned after successful OTP verify.', max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='otp_verific_phone_7f1a5f_idx'), models.Index(fields=['verification_token'], name='otp_verific_verific_43260e_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.utils.validators.validate_sa_phone])),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('owner', 'Owner'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of permissions for this user')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx')],
            },
        ),
    ]
