# Generated by Django 6.0.3 on 2026-03-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('registration', 'Registration'), ('change_phone', 'Change Phone'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
