# Generated by Django 6.0.3 on 2026-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('change_phone', 'Change Phone'), ('password_reset', 'Password Reset'), ('owner_register', 'Owner Register')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, help_text='Short-lived token returned after successful OTP verify.', max_length=64, null=True, unique=True),
        ),
    ]
